appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: CalHStRXH5SPLsMm9axK7rsMVF5ryGJGaAvrU4cfbPgoNddT7WwI1GkNyOYxN9MjOEU9zKkYX2PPRZG9eKlOthasigAQKO+d4rnaZGJMPIn7DTXfVOdF8LDA7t8r2U3/lxpGFeZ+WFz6d1pHSJ9ZtzNeQeDgiW7zZ641MWfDsZkWUwzUvxJB/LFYE+Wx3cUAXLsGW2WVkjaeUXpZbxvscstzEuuDfKA3jG5vdaQq3YEtaEHIpnYPkT/gi0YGa4aV7M8htSoeWvyppYZZMHS5fYynOJ24QUqA83nbha0ZGl5QS1j+y66BoELBsM/bn1VzW6e88Xks+HDTCewBagM2pAlI6vIEYuTFBMtvU88fxQGRs40BGz8tzPRR1jljKOO22beQC/+D3an1J/h2bvFyfFJF+wPVs5ITYMe29N3DxOjXU+F1FQgl3x2qWVN2VCUBFQND87IH9pKdv9+AVnFMJI6eZB8zaG9L0uE0DuAPqO5tF3mYCJt9xZmevIgaBegQEK3sR5zdVPx0jrfG/unUKtD/c1BbqRaChXSxAbfq2xjcXVEQzoYmgiza3NmtJ6UZ0zc2H5Xky1dHsHlKAqHaespo9gag5rQ3Q5ez9Z4OVQsG6VXD2ZJrwQvkaeub2wJuNJunufrIvwR+AzWRiOx9HT0VcqI2GQhPvJNRKI3IrGc=}
